### ISSUE TITLE
Correcao do cadastro de professor

### ISSUE THREAD

**Issue by emivaljr** [kabrabom/web#137]
@vlbgomes: O que eu tenho observado nos cadastros existentes do Kabrabom é que hoje a profissão é Professor de.... e o que eu vejo na descricao é que ele dá aula de varias disciplinas.
Minha sugestão é, a profissão ser Professor Particular e os servicos serem, Aula de Matemática, Aula de Portugues..... conforme tinha sugerido anteriormente. Dai vai ficar mais fácil achar um professor que dê aula de uma disciplina na busca. Hoje o professor acaba escolhendo uma profissão apenas. 
Pra os usuários já cadastrados, poderiamos dizer que vamos ajustar isso no banco de dados, de forma que eles serão ajustados pela descricao. 
Ex.
http://www.kabrabom.com.br/professional_professions/119
http://www.kabrabom.com.br/professional_professions/25

**Comment by vlbgomes** [comment]
@emivaljr conforme alinhado criamos o "Professor Multidisciplinar"
