### ISSUE TITLE
Visualização descrição prestador

### ISSUE THREAD

**Issue by vlbgomes** [kabrabom/web#24]
A descrição da visualização do prestador está sendo escondida pelos tipos de serviços quando a mesma é muito extensa. Delimitar as colunas da descrição para que isso não ocorra.

![image](https://cloud.githubusercontent.com/assets/13422730/23575636/c04eac2e-006e-11e7-8a4e-38a4d27d0843.png)

**Comment by emivaljr** [comment]
@vlbgomes : se vc encontrar uma palavra desse tamanho na linha portuguesa eu arrumo....kkkkk Esse tipo de teste é pra quebrar o sistema mesmo, mas não sei se devemos limitar a quantidade de caracteres da descricao dessa forma. Na verdade futuramente eu gostaria de deixar o usuário incluir html na descricão tipo um anuncio mesmo.

**Comment by vlbgomes** [comment]
@emivaljr: não tinha me ligado que era apenas uma palavra. Vou fazer um teste com um anúncio normal, mas com muitas palavras!

**Comment by vlbgomes** [comment]
Fiz o teste com as palavras e foi feita a quebra de linha de maneira correta!
