### ISSUE TITLE
Restrição campos formulários

### ISSUE THREAD

**Issue by vlbgomes** [kabrabom/web#26]
Campos numéricos estão aceitando outros valores. Tem que avaliar todos os formulários do sistema.

**Comment by emivaljr** [comment]
@vlbgomes: temos que entender se estamos com problema nas mascaras, pq elas na teoria já impedem de colocar valores não numericos. Ou se os campos que vc tá falando são outros campos que não tem mascara.

**Comment by vlbgomes** [comment]
@emivaljr: Por exemplo o Número do Endereço não tem máscara. Este foi o campo que peguei como referência, por isso sugeri avaliar o resto! Uma coisa que tem ocorrido também é na mensagem de envio para o prestador de serviço, uma vez submetida e retorna com erros de validação a máscara para de funcionar e abre para digitar letras!

**Comment by emivaljr** [comment]
Pelo menos nos formularios que eu implementei todos tinham mascara para campos onde há mascara. Para o campo de numero foi proposital, pq já vi muitos enderecos que o numero possui letras ou caracteres especiais. tipo numero 2-B ou apartamento N504. Agora sobre a mascara parar de funcionar após a submissão, ai é um erro mesmo precisamos investigar.

**Comment by vlbgomes** [comment]
@emivaljr: Criei a issue para não passar batido. É um ponto de atenção! Pode deixar que eu faço essa avaliação.

**Comment by vlbgomes** [comment]
Fechando, pois após alguns feedbacks dos usuários resolvemos reformular o cadastro!
