### ISSUE TITLE
Camelcase no início de frase

### ISSUE THREAD

**Issue by vlbgomes** [kabrabom/web#56]
Para evitar uma aparência ruim do profissional por parte do usuário seria bom analisar os pontos da aplicação que é apresentado dados de texto começando com letra minúscula e aplicar CamelCase. Para evitar isso:

![image](https://cloud.githubusercontent.com/assets/13422730/24053058/680332f8-0b16-11e7-92bb-6307db31ffc2.png)

![image](https://cloud.githubusercontent.com/assets/13422730/24053092/8c2b38e2-0b16-11e7-9bc7-1b24ef929756.png)

**Comment by emivaljr** [comment]
@vlbgomes Acho interessante já fazermos o tratamento no momento de gravar a informacão no banco de dados. Temos que avaliar coisas simples, como Colocar letra maiuscula no inicio das frases e tentar colocar o restante em minuscula. Uma coisa que eu vi no Mercado Livre é que no titulo dos anuncios ele padroniza colocando todas as palavras iniciando com a letra maiuscula. E nos textos só a primeira palavra.

**Comment by emivaljr** [comment]
https://apidock.com/rails/String/titleize

**Comment by emivaljr** [comment]
@vlbgomes Coloquei o tratamento to titleize na hora do cadastro do usuario. Talvez seja o caso de arrumarmos o nome dos usuarios antigos.

**Comment by vlbgomes** [comment]
@emivaljr Show! Vou criar o script para regularizar os cadastros antigos!

**Comment by vlbgomes** [comment]
Script abaixo foi executado com sucesso e corrigido os cadastros legados:
select 'UPDATE USERS set name = '' '||
(replace(initcap(replace(name, '_', ' ')), ' ', ' '))
||' '' WHERE name = '''||name||''';'
FROM users;
