### ISSUE TITLE
Melhorar cadastro usuário

### ISSUE THREAD

**Issue by vlbgomes** [kabrabom/web#72]
@kabrabom/donos-kabrabom 
@emivaljr e @edu1006 
Alterar o cadastro inicial para apresentar: Nome (precisa informar que é o Nome da Pessoa e não Fantasia de maneira sutil), Email e Senha (neste campo poderíamos ver aquele campo que mostra a senha do usuário para evitar um campo de confirmação de senha). Após cadastrado o usuário venha aparecer a mesma mensagem de boas vindas, mas que seja apresentado dois botões em destaque (Cadastrar meu Serviço (Azul ou Vermelho) e Voltar para Navegar(Verde)).

**Comment by vlbgomes** [comment]
Exemplo de olho na senha!!!

Usando jquery, faça o seguinte:

> $( "#olho" ).mousedown(function() {
>   $("#senha").attr("type", "text");
> });
> 
> $( "#olho" ).mouseup(function() {
>   $("#senha").attr("type", "password");
> });

Exemplo Completo:

> var senha = $('#senha');
> var olho= $("#olho");
> 
> olho.mousedown(function() {
>   senha.attr("type", "text");
> });
> 
> olho.mouseup(function() {
>   senha.attr("type", "password");
> });
> // para evitar o problema de arrastar a imagem e a senha continuar exposta, 
> //citada pelo nosso amigo nos comentários
> $( "#olho" ).mouseout(function() { 
>   $("#senha").attr("type", "password");
> });
> <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
> <input type="password" value="123456789" id="senha">
> <img id="olho" src="link_da_imagem"/>

**Comment by emivaljr** [comment]
@vlbgomes Falta algo pra fechar essa issue?

**Comment by vlbgomes** [comment]
@emivaljr : Falta apenas colocar o cadastro da foto de perfil. Esqueci de comentar aqui.

**Comment by vlbgomes** [comment]
@kabrabom/donos-kabrabom : Foi colocada a imagem para upload, mas para imagens com alta resolução  o upload ficou extremamento lento. Agora falta melhorar apenas isso!

**Comment by vlbgomes** [comment]
Testado!
