### ISSUE TITLE
Validação de E-mail no cadastro Usuário

### ISSUE THREAD

**Issue by vlbgomes** [kabrabom/web#75]
Melhorar a validação de e-mail durante o cadastro do usuário. Para evitar o ocorrido abaixo:

![image](https://cloud.githubusercontent.com/assets/13422730/24340083/04cc09ea-1286-11e7-8459-24944b33f2ff.png)

**Comment by emivaljr** [comment]
@vlbgomes A melhor forma de evitar e-mails invalidos é a confirmacao do cadastro via e-mail. Mas isso é mais uma coisa pro cara fazer. Porém garante que o cara não vai usar um e-mail inválido pro cadastro do kabrabom.

**Comment by vlbgomes** [comment]
@emivaljr É verdade, mas a gente pode trabalhar com um tempo em que ele pode ficar sem confirmação. Do contrário o cadastro dele é invalidado.

**Comment by emivaljr** [comment]
Na verdade o regex que fazia a validacao do e-mail para a tela de contato estava muito restritivo. Estou utilizando um gem especifico para validacao de e-mail, e o e-mail acima é considerado válido. Podemos cadastrar uma melhoria futura para fazer o registro em 2 passos, mas não é o caso desse erro.
