### ISSUE TITLE
Cadastro de Serviço não funciona

### ISSUE THREAD

**Issue by vlbgomes** [kabrabom/web#8]
Quando no cadastro do serviço, nada acontece ao clicar no botão Cadastro de Serviço. Deveria abrir uma modal disponibilizando o cadastro para o usuário.

**Comment by emivaljr** [comment]
@vlbgomes Esse erro continua acontecendo? É uma situacao, ou navegador especifico? Não consegui compreender quando que a situacao acontece.

**Comment by vlbgomes** [comment]
@emivaljr eu não sei te responder porque lá no trabalharam mudaram o proxy e não tá acontecendo mais. Eu não fechei esse porque não queria esquecer! É um bug que a gente tem ciência do acontecimento, mas não sabemos a causa!

**Comment by emivaljr** [comment]
@vlbgomes Será que não era uma configuracao errada feita na rede do Sicoob especificamente? Ou você conseguiu simular em outro ambiente?

**Comment by vlbgomes** [comment]
@emivaljr : Não consegui simular não! Onde a gente conseguia simular não dá mais! Eu sei que tem a ver com aquele problema de cross http secure.

**Comment by vlbgomes** [comment]
Fechando porque o erro não ocorreu mais
